name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      environment_input:
        description: '環境を選択してください'
        required: false
        default: 'env1'
        type: environment

jobs:
  echo_input:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment_input }}
    steps:
      - name: echo input
        run: |
          echo ${{ vars.TEST }}
