name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'テスト入力'
        required: true
        default: 'default_value'
        type: string

jobs:
  echo_input:
    runs-on: ubuntu-latest
    steps:
      - name: echo input
        run: |
          echo "Input value: ${{ github.event.inputs.test_input }}"
