name: Test Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run the workflow"
        required: true
        default: "development"
        type: environment
      message:
        description: "Message to display"
        required: true
        type: string

jobs:
  test_job:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Hello World
        run: echo "Hello, ${{ vars.TEST }}!"
